import { Inter } from "next/font/google";
import "./globals.css";
import "./styles/post.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "my App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
        <nav className="nav">
          <Link href="/">Home</Link>
          <Link href="articles">Articles</Link>
          <Link href="posts">Posts</Link>
        </nav>
        {children}
        </body>
		</html>
	);
}
